### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [iAcn/MBEStyle#2]
It would be great to have this theme available on F-Droid :)
Do you think that's doable?

https://f-droid.org/

**Comment by meolunr** [comment]
@picsi Yes, me too. I will spare some time to upload to the F-Droid

**Comment by nicolasmaia** [comment]
@rudloff might be able to help if you have questions

**Comment by Rudloff** [comment]
Very nice icon pack!
I had a look at the code and it seems to comply with our inclusion policy.

@picsi Can you please open a [RFP](https://gitlab.com/fdroid/rfp/issues)?

**Comment by nicolasmaia** [comment]
@Rudloff here you go https://gitlab.com/fdroid/rfp/issues/914

**Comment by meolunr** [comment]
@picsi OK, thank you very much for your help :)

**Comment by Rudloff** [comment]
@iAcn Would it be possible to add a Git tag for 1.7.3? We can't build 1.7.2 because of https://github.com/iAcn/MBEStyle/issues/4.

**Comment by meolunr** [comment]
@Rudloff I have just added a new Git Tag for 1.7.2.

**Comment by Rudloff** [comment]
Perfect, thank you!
