### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by by-syk** [iAcn/MBEStyle#4]
`/res/drawable-nodpi/Spotify.png` -> `spotify.png`

**Comment by Rudloff** [comment]
It looks like this was fixed in ab453adf243f0c5b58e4e9944c799a96264f5f65 and 2d83cce1b75a7f632af5348f4db92581a3ac239d.

**Comment by meolunr** [comment]
@Rudloff Yes, the error has been fixed.
