### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by lanaschuhmacher** [iAcn/MBEStyle#9]
Do you plan to add English strings?

**Comment by meolunr** [comment]
Yes. As I said in reply to your email, I'll start working at the end of this month. :)

**Comment by lanaschuhmacher** [comment]
Great, that are amazing news! 😎
I can help you with translating them into German then. 😉

**Comment by Fernandus91** [comment]
I can hep too translating it into Italian.

**Comment by meolunr** [comment]
@Fernandus91 Wow, Thank you! 
You could do it after I pushed the English Translation.

**Comment by happysmash27** [comment]
I can help with Esperanto myself.

**Comment by ligan92** [comment]
I could help you translate from Chinese to English/French, if needed.

**Comment by meolunr** [comment]
@ligan92 I will translate it to English at tonight and you could help me translate into French. Thanks!
